backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
      
  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Name", name: "title", widget: "string", required: true}
      
  - name: "blog"
    label: "Blog"
    folder: "content/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: 'json'
    fields:
      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - {label: "Author Name", name: "name", widget: "relation", collection: "authors", searchFields: ["title"], displayFields: ["title"], valueField: "title", required: true}
          - {label: "Profile", name: "profile", widget: "image", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date", default: "", format: "MMMM Do YYYY", required: true}
      - {label: "Featured Image", name: "hero", widget: "image", required: true}
      - {label: "Tags", name: "tags", widget: "list", default: ["blog"]}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "SEO Description", name: "description", widget: "text"}

  - name: "events"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Event Date", name: "date", widget: "datetime", default: "", format: "MMMM Do YYYY HH:mmZ", required: true}
      - {label: "Featured Image", name: "hero", widget: "image", required: true}
      - {label: "Event Location", name: "location", widget: "string", required: true}
      - {label: "Event Description", name: "body", widget: "markdown", required: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Gallery Name", name: "title", widget: "string", default: "Gallery"}
      - label: "Images"
        name: "image"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: true}
              - {label: "Description", name: "description", widget: "string"}
