backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:

  - name: "author"
    label: "Author"
    folder: "content/authors"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Avatar", name: "avatar", widget: "image", required: true}
      - {label: "Name", name: "name", widget: "string", required: true}
      - {label: "Short Bio", name: "bio", widget: "text", required: false}

  - name: "blog"
    label: "Blog"
    folder: "content/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: 'json'
    fields:
      - {label: "Author", name: "author", widget: "relation", collection: "author", searchFields: "name", valueField: "name", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date", default: "", format: "MMMM Do YYYY", required: true}
      - {label: "Featured Image", name: "hero", widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      
  - name: "gallery"
    label: "Gallery Thumbnail"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Image Title", name: "title", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date", default: "", format: "MMMM Do YYYY", required: false}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Image Description", name: "description", widget: "text", required: false}

  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Event Date", name: "date", widget: "datetime", default: "", format: "MMMM Do YYYY HH:mmZ", required: true}
      - {label: "Featured Image", name: "hero", widget: "image", required: true}
      - {label: "Event Location", name: "location", widget: "string", required: true}
      - {label: "Event Description", name: "body", widget: "markdown", required: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

    